name = "sharoushi-task-manager"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js"
pages_build_output_dir = "./dist"

# Account ID for deployment
account_id = "a2beb7b88e3c7a9888e6ec0849498ce7"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "sharoushi-task-manager-db"
database_id = "27bfba63-7b20-402a-ba8b-5c5efe32ff67"

# Environment variables for production
[env.production]
name = "sharoushi-task-manager"

[env.production.vars]
ENVIRONMENT = "production"
APP_URL = "https://sharoushi-task-manager.pages.dev"
REDIRECT_URI = "https://sharoushi-task-manager.pages.dev/auth/callback"

# Local development environment
[env.local]
[env.local.vars]
ENVIRONMENT = "development"
APP_URL = "http://localhost:8788"
REDIRECT_URI = "http://localhost:8788/auth/callback"